"""empty message

Revision ID: 15ea59121b0a
Revises: b21aa8487217
Create Date: 2018-03-15 15:20:02.097606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15ea59121b0a'
down_revision = 'b21aa8487217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('activation_status', sa.String(length=256), nullable=True))
    op.add_column('recruiters', sa.Column('activation_status', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruiters', 'activation_status')
    op.drop_column('companies', 'activation_status')
    # ### end Alembic commands ###
