"""empty message

Revision ID: 6df871eca7d5
Revises: ad6f4a30f4a3
Create Date: 2018-03-16 16:28:18.699139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6df871eca7d5'
down_revision = 'ad6f4a30f4a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('status', sa.String(length=256), nullable=True))
    op.drop_column('companies', 'activation_status')
    op.add_column('job_recruiter', sa.Column('status', sa.String(length=256), nullable=True))
    op.drop_column('job_recruiter', 'action_status')
    op.drop_column('job_recruiter_candidate', 'submitted')
    op.add_column('jobs', sa.Column('status', sa.String(length=256), nullable=True))
    op.add_column('recruiters', sa.Column('status', sa.String(length=256), nullable=True))
    op.drop_column('recruiters', 'activation_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruiters', sa.Column('activation_status', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('recruiters', 'status')
    op.drop_column('jobs', 'status')
    op.add_column('job_recruiter_candidate', sa.Column('submitted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('job_recruiter', sa.Column('action_status', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('job_recruiter', 'status')
    op.add_column('companies', sa.Column('activation_status', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('companies', 'status')
    # ### end Alembic commands ###
