"""empty message

Revision ID: 805b37ac470b
Revises: 
Create Date: 2018-03-22 10:38:27.483497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '805b37ac470b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_table('department_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_types_name'), 'department_types', ['name'], unique=False)
    op.create_table('position_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_types_name'), 'position_types', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('recruiters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiters_user_id'), 'recruiters', ['user_id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=256), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_user_id'), 'companies', ['user_id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_user_id'), 'candidates', ['user_id'], unique=False)
    op.create_table('candidate_resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('resume_name', sa.String(length=256), nullable=True),
    sa.Column('resume_url', sa.String(length=256), nullable=True),
    sa.Column('redacted_resume_url', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_resumes_candidate_id'), 'candidate_resumes', ['candidate_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('recruiter_description', sa.Text(), nullable=True),
    sa.Column('questions', sa.Text(), nullable=True),
    sa.Column('open_positions', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=256), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['position_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_company_id'), 'jobs', ['company_id'], unique=False)
    op.create_index(op.f('ix_jobs_position_id'), 'jobs', ['position_id'], unique=False)
    op.create_table('job_recruiter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('recruiter_id', sa.Integer(), nullable=True),
    sa.Column('resume_limit', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=256), nullable=True),
    sa.Column('guid', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_recruiter_guid'), 'job_recruiter', ['guid'], unique=False)
    op.create_index(op.f('ix_job_recruiter_job_id'), 'job_recruiter', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_recruiter_recruiter_id'), 'job_recruiter', ['recruiter_id'], unique=False)
    op.create_table('job_recruiter_candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('soft_delete', sa.Boolean(), nullable=True),
    sa.Column('job_recruiter_id', sa.Integer(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('candidate_resume_id', sa.Integer(), nullable=True),
    sa.Column('marvel_name', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['candidate_resume_id'], ['candidate_resumes.id'], ),
    sa.ForeignKeyConstraint(['job_recruiter_id'], ['job_recruiter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_recruiter_candidate_candidate_id'), 'job_recruiter_candidate', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_job_recruiter_candidate_candidate_resume_id'), 'job_recruiter_candidate', ['candidate_resume_id'], unique=False)
    op.create_index(op.f('ix_job_recruiter_candidate_job_recruiter_id'), 'job_recruiter_candidate', ['job_recruiter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_recruiter_candidate_job_recruiter_id'), table_name='job_recruiter_candidate')
    op.drop_index(op.f('ix_job_recruiter_candidate_candidate_resume_id'), table_name='job_recruiter_candidate')
    op.drop_index(op.f('ix_job_recruiter_candidate_candidate_id'), table_name='job_recruiter_candidate')
    op.drop_table('job_recruiter_candidate')
    op.drop_index(op.f('ix_job_recruiter_recruiter_id'), table_name='job_recruiter')
    op.drop_index(op.f('ix_job_recruiter_job_id'), table_name='job_recruiter')
    op.drop_index(op.f('ix_job_recruiter_guid'), table_name='job_recruiter')
    op.drop_table('job_recruiter')
    op.drop_index(op.f('ix_jobs_position_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_candidate_resumes_candidate_id'), table_name='candidate_resumes')
    op.drop_table('candidate_resumes')
    op.drop_index(op.f('ix_candidates_user_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_companies_user_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_recruiters_user_id'), table_name='recruiters')
    op.drop_table('recruiters')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_position_types_name'), table_name='position_types')
    op.drop_table('position_types')
    op.drop_index(op.f('ix_department_types_name'), table_name='department_types')
    op.drop_table('department_types')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
