"""empty message

Revision ID: ad6f4a30f4a3
Revises: 15ea59121b0a
Create Date: 2018-03-15 22:56:34.343260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6f4a30f4a3'
down_revision = '15ea59121b0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_recruiter', sa.Column('guid', sa.String(length=256), nullable=True))
    op.create_index(op.f('ix_job_recruiter_guid'), 'job_recruiter', ['guid'], unique=False)
    op.add_column('jobs', sa.Column('questions', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('recruiter_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'recruiter_description')
    op.drop_column('jobs', 'questions')
    op.drop_index(op.f('ix_job_recruiter_guid'), table_name='job_recruiter')
    op.drop_column('job_recruiter', 'guid')
    # ### end Alembic commands ###
