"""empty message

Revision ID: b2596e8992f8
Revises: 6df871eca7d5
Create Date: 2018-03-18 16:02:34.831612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2596e8992f8'
down_revision = '6df871eca7d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_resumes', sa.Column('resume_name', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_resumes', 'resume_name')
    # ### end Alembic commands ###
