"""empty message

Revision ID: e916d1c47cf8
Revises: 
Create Date: 2018-03-13 20:28:45.969718

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e916d1c47cf8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_company_user_id'), 'company', ['user_id'], unique=False)
    op.create_foreign_key(None, 'company', 'users', ['user_id'], ['id'])
    op.drop_index('ix_users_company_id', table_name='users')
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.drop_column('users', 'company_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('users_ibfk_1', 'users', 'company', ['company_id'], ['id'])
    op.create_index('ix_users_company_id', 'users', ['company_id'], unique=False)
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_index(op.f('ix_company_user_id'), table_name='company')
    op.drop_column('company', 'user_id')
    # ### end Alembic commands ###
